Repository KiaraL2/GitTest, pull requests merged in 2024-05, with the labels that each got.

#5 Document: 기능정의
  new기획.md
Labels: documentation

#13 docs: 240522회의록추가
  20240522.md
Labels: 📃 Docs

#14 feat: req.html추가
  req.html
Labels: 🎨 Html&css

#16 feat : 녹녹로고추가
  녹녹 브랜드로고-001.png
Labels: 🎨 Html&css

#17 chore: 20240522.md 수정
  20240522.md
Labels: 📃 Docs

#18 docs: 부분 마크업 추가
  헤더 html.txt
  헤더 스타일.txt
Labels: 🎨 Html&css

#20 docs: 0523 회의록 추가
  회의록/20240522.md
  회의록/20240523.md
Labels: 📃 Docs

#21 update: 20240523.md 수정
  회의록/20240523.md
Labels: 📃 Docs

#22 feat : 마이페이지 마크업
  Style.css
  mypage.html
Labels: 🎨 Html&css
